/**
 * Tradução EN→PT dos nomes de países da api-football (que não tem i18n).
 * Aplicado ao mapear ligas; nomes não mapeados caem no original.
 */
const COUNTRY_PT: Record<string, string> = {
  'World': 'Mundo',
  'Brazil': 'Brasil',
  'England': 'Inglaterra',
  'Spain': 'Espanha',
  'Italy': 'Itália',
  'Germany': 'Alemanha',
  'France': 'França',
  'Portugal': 'Portugal',
  'Netherlands': 'Países Baixos',
  'Belgium': 'Bélgica',
  'Scotland': 'Escócia',
  'Wales': 'País de Gales',
  'Ireland': 'Irlanda',
  'Northern Ireland': 'Irlanda do Norte',
  'Argentina': 'Argentina',
  'Uruguay': 'Uruguai',
  'Paraguay': 'Paraguai',
  'Chile': 'Chile',
  'Colombia': 'Colômbia',
  'Peru': 'Peru',
  'Ecuador': 'Equador',
  'Bolivia': 'Bolívia',
  'Venezuela': 'Venezuela',
  'Mexico': 'México',
  'USA': 'Estados Unidos',
  'Canada': 'Canadá',
  'Costa Rica': 'Costa Rica',
  'Honduras': 'Honduras',
  'Guatemala': 'Guatemala',
  'Panama': 'Panamá',
  'Jamaica': 'Jamaica',
  'Turkey': 'Turquia',
  'Russia': 'Rússia',
  'Ukraine': 'Ucrânia',
  'Greece': 'Grécia',
  'Switzerland': 'Suíça',
  'Austria': 'Áustria',
  'Denmark': 'Dinamarca',
  'Sweden': 'Suécia',
  'Norway': 'Noruega',
  'Finland': 'Finlândia',
  'Iceland': 'Islândia',
  'Poland': 'Polônia',
  'Czech-Republic': 'Tchéquia',
  'Croatia': 'Croácia',
  'Serbia': 'Sérvia',
  'Romania': 'Romênia',
  'Bulgaria': 'Bulgária',
  'Hungary': 'Hungria',
  'Slovakia': 'Eslováquia',
  'Slovenia': 'Eslovênia',
  'Bosnia': 'Bósnia e Herzegovina',
  'Albania': 'Albânia',
  'North-Macedonia': 'Macedônia do Norte',
  'Montenegro': 'Montenegro',
  'Kosovo': 'Kosovo',
  'Moldova': 'Moldávia',
  'Belarus': 'Belarus',
  'Lithuania': 'Lituânia',
  'Latvia': 'Letônia',
  'Estonia': 'Estônia',
  'Luxembourg': 'Luxemburgo',
  'Malta': 'Malta',
  'Cyprus': 'Chipre',
  'Georgia': 'Geórgia',
  'Armenia': 'Armênia',
  'Azerbaijan': 'Azerbaijão',
  'Kazakhstan': 'Cazaquistão',
  'Israel': 'Israel',
  'Japan': 'Japão',
  'China': 'China',
  'South-Korea': 'Coreia do Sul',
  'Saudi-Arabia': 'Arábia Saudita',
  'Qatar': 'Catar',
  'United-Arab-Emirates': 'Emirados Árabes Unidos',
  'Iran': 'Irã',
  'Iraq': 'Iraque',
  'Jordan': 'Jordânia',
  'Kuwait': 'Kuwait',
  'Bahrain': 'Bahrein',
  'Oman': 'Omã',
  'India': 'Índia',
  'Indonesia': 'Indonésia',
  'Thailand': 'Tailândia',
  'Vietnam': 'Vietnã',
  'Malaysia': 'Malásia',
  'Singapore': 'Singapura',
  'Australia': 'Austrália',
  'New-Zealand': 'Nova Zelândia',
  'Egypt': 'Egito',
  'Morocco': 'Marrocos',
  'Algeria': 'Argélia',
  'Tunisia': 'Tunísia',
  'Nigeria': 'Nigéria',
  'South-Africa': 'África do Sul',
  'Ghana': 'Gana',
  'Cameroon': 'Camarões',
  'Ivory-Coast': 'Costa do Marfim',
  'Senegal': 'Senegal',
}

export function translateCountry(name: string): string {
  if (COUNTRY_PT[name]) return COUNTRY_PT[name]
  const spaced = name.replace(/-/g, ' ')
  return COUNTRY_PT[spaced] ?? name
}
